package pojo;
// Generated 06-feb-2017 10:24:18 by Hibernate Tools 4.3.1



/**
 * BilllLines generated by hbm2java
 */
public class BilllLines  implements java.io.Serializable {


     private BilllLinesId id;
     private Bill bill;
     private Pets pets;
     private Products products;
     private Integer quantity;
     private Double price;
     private Integer taxes;
     private Integer discount;
     private String observations;

    public BilllLines() {
    }

	
    public BilllLines(BilllLinesId id, Bill bill, Products products) {
        this.id = id;
        this.bill = bill;
        this.products = products;
    }
    public BilllLines(BilllLinesId id, Bill bill, Pets pets, Products products, Integer quantity, Double price, Integer taxes, Integer discount, String observations) {
       this.id = id;
       this.bill = bill;
       this.pets = pets;
       this.products = products;
       this.quantity = quantity;
       this.price = price;
       this.taxes = taxes;
       this.discount = discount;
       this.observations = observations;
    }
   
    public BilllLinesId getId() {
        return this.id;
    }
    
    public void setId(BilllLinesId id) {
        this.id = id;
    }
    public Bill getBill() {
        return this.bill;
    }
    
    public void setBill(Bill bill) {
        this.bill = bill;
    }
    public Pets getPets() {
        return this.pets;
    }
    
    public void setPets(Pets pets) {
        this.pets = pets;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Integer getTaxes() {
        return this.taxes;
    }
    
    public void setTaxes(Integer taxes) {
        this.taxes = taxes;
    }
    public Integer getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }
    public String getObservations() {
        return this.observations;
    }
    
    public void setObservations(String observations) {
        this.observations = observations;
    }




}


