package pojo;
// Generated 06-feb-2017 10:24:18 by Hibernate Tools 4.3.1



/**
 * BillLines generated by hbm2java
 */
public class BillLines  implements java.io.Serializable {


     private int id;
     private int idbill;
     private int idpet;
     private int idproduct;
     private int quantity;
     private double price;
     private int taxes;
     private int discount;
     private String observations;

    public BillLines() {
    }

	
    public BillLines(int id, int bill, int idproduct) {
        this.id = id;
        this.idbill = bill;
        this.idproduct = idproduct;
    }
    public BillLines(int id, int idbill, int idpet, int idproduct, int quantity, Double price, int taxes, int discount, String observations) {
       this.id = id;
       this.idbill = idbill;
       this.idpet = idpet;
       this.idproduct = idproduct;
       this.quantity = quantity;
       this.price = price;
       this.taxes = taxes;
       this.discount = discount;
       this.observations = observations;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getBill() {
        return this.idbill;
    }
    
    public void setBill(int idbill) {
        this.idbill = idbill;
    }
    public int getPets() {
        return this.idpet;
    }
    
    public void setPets(int idpet) {
        this.idpet = idpet;
    }
    public int getProducts() {
        return this.idproduct;
    }
    
    public void setProducts(int idproducts) {
        this.idproduct = idproducts;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public int getTaxes() {
        return this.taxes;
    }
    
    public void setTaxes(int taxes) {
        this.taxes = taxes;
    }
    public int getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(int discount) {
        this.discount = discount;
    }
    public String getObservations() {
        return this.observations;
    }
    
    public void setObservations(String observations) {
        this.observations = observations;
    }




}


