package pojo;
// Generated 06-feb-2017 10:24:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Dates generated by hbm2java
 */
public class Dates  implements java.io.Serializable {


     private DatesId id;
     private Person person;
     private Date hour;
     private String observations;

    public Dates() {
    }

	
    public Dates(DatesId id, Person person, Date hour) {
        this.id = id;
        this.person = person;
        this.hour = hour;
    }
    public Dates(DatesId id, Person person, Date hour, String observations) {
       this.id = id;
       this.person = person;
       this.hour = hour;
       this.observations = observations;
    }
   
    public DatesId getId() {
        return this.id;
    }
    
    public void setId(DatesId id) {
        this.id = id;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public Date getHour() {
        return this.hour;
    }
    
    public void setHour(Date hour) {
        this.hour = hour;
    }
    public String getObservations() {
        return this.observations;
    }
    
    public void setObservations(String observations) {
        this.observations = observations;
    }




}


