package pojo;
// Generated 06-feb-2017 10:24:18 by Hibernate Tools 4.3.1

import java.sql.Blob;
import java.util.Date;

/**
 * Doc generated by hbm2java
 */
public class Doc implements java.io.Serializable {

    private int iddoc;
    private int idcons;
    private String date_doc;
    private String description;
    public byte[] fileattached;
    private Consultation consultation;
    public java.sql.Blob fileattached2;

    public Doc() {
    }

    public Doc(int iddoc, int idcons, String date_doc, String description, byte[] fileattached, Consultation consultation, Blob fileattached2) {
        this.iddoc = iddoc;
        this.idcons = idcons;
        this.date_doc = date_doc;
        this.description = description;
        this.fileattached = fileattached;
        this.consultation = consultation;
        this.fileattached2 = fileattached2;
    }

    public Doc(int iddoc, int idcons, String date_doc, String description, byte[] fileattached, Consultation consultation) {
        this.iddoc = iddoc;
        this.idcons = idcons;
        this.date_doc = date_doc;
        this.description = description;
        this.fileattached = fileattached;
        this.consultation = consultation;
    }

    public int getIddoc() {
        return iddoc;
    }

    public void setIddoc(int iddoc) {
        this.iddoc = iddoc;
    }

    public int getIdcons() {
        return idcons;
    }

    public void setIdcons(int idcons) {
        this.idcons = idcons;
    }

    public String getDate_doc() {
        return date_doc;
    }

    public void setDate_doc(String date_doc) {
        this.date_doc = date_doc;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public byte[] getFileattached() {
        return fileattached;
    }

    public void setFileattached(byte[] fileattached) {
        this.fileattached = fileattached;
    }

    public Consultation getConsultation() {
        return consultation;
    }

    public void setConsultation(Consultation consultation) {
        this.consultation = consultation;
    }

    public Blob getFileattached2() {
        return fileattached2;
    }

    public void setFileattached2(Blob fileattached2) {
        this.fileattached2 = fileattached2;
    }

}
