package pojo;
// Generated 06-feb-2017 10:24:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pets generated by hbm2java
 */
public class Pets  implements java.io.Serializable {


     private Integer idpets;
     private Person person;
     private String name;
     private String animal;
     private Boolean gender;
     private String race;
     private String colour;
     private Date birthDate;
     private Set billlLineses = new HashSet(0);
     private Set consultations = new HashSet(0);
     private Set vaccineses = new HashSet(0);

    public Pets() {
    }

	
    public Pets(Person person, String name, String animal) {
        this.person = person;
        this.name = name;
        this.animal = animal;
    }
    public Pets(Person person, String name, String animal, Boolean gender, String race, String colour, Date birthDate, Set billlLineses, Set consultations, Set vaccineses) {
       this.person = person;
       this.name = name;
       this.animal = animal;
       this.gender = gender;
       this.race = race;
       this.colour = colour;
       this.birthDate = birthDate;
       this.billlLineses = billlLineses;
       this.consultations = consultations;
       this.vaccineses = vaccineses;
    }
   
    public Integer getIdpets() {
        return this.idpets;
    }
    
    public void setIdpets(Integer idpets) {
        this.idpets = idpets;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAnimal() {
        return this.animal;
    }
    
    public void setAnimal(String animal) {
        this.animal = animal;
    }
    public Boolean getGender() {
        return this.gender;
    }
    
    public void setGender(Boolean gender) {
        this.gender = gender;
    }
    public String getRace() {
        return this.race;
    }
    
    public void setRace(String race) {
        this.race = race;
    }
    public String getColour() {
        return this.colour;
    }
    
    public void setColour(String colour) {
        this.colour = colour;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public Set getBilllLineses() {
        return this.billlLineses;
    }
    
    public void setBilllLineses(Set billlLineses) {
        this.billlLineses = billlLineses;
    }
    public Set getConsultations() {
        return this.consultations;
    }
    
    public void setConsultations(Set consultations) {
        this.consultations = consultations;
    }
    public Set getVaccineses() {
        return this.vaccineses;
    }
    
    public void setVaccineses(Set vaccineses) {
        this.vaccineses = vaccineses;
    }




}


