package pojo;
// Generated 06-feb-2017 10:24:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Vaccines generated by hbm2java
 */
public class Vaccines  implements java.io.Serializable {


     private Integer idvac;
     private Pets pets;
     private Vaccinecal vaccinecal;
     private Date date;
     private String observaciones;

    public Vaccines() {
    }

	
    public Vaccines(Pets pets, Vaccinecal vaccinecal, Date date) {
        this.pets = pets;
        this.vaccinecal = vaccinecal;
        this.date = date;
    }
    public Vaccines(Pets pets, Vaccinecal vaccinecal, Date date, String observaciones) {
       this.pets = pets;
       this.vaccinecal = vaccinecal;
       this.date = date;
       this.observaciones = observaciones;
    }
   
    public Integer getIdvac() {
        return this.idvac;
    }
    
    public void setIdvac(Integer idvac) {
        this.idvac = idvac;
    }
    public Pets getPets() {
        return this.pets;
    }
    
    public void setPets(Pets pets) {
        this.pets = pets;
    }
    public Vaccinecal getVaccinecal() {
        return this.vaccinecal;
    }
    
    public void setVaccinecal(Vaccinecal vaccinecal) {
        this.vaccinecal = vaccinecal;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


